name: Latest stack overflow activity
on:
  schedule:
    # Runs every Monday at midnight
    - cron: '0 0 * * 1'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: 'STACKOVERFLOW'
          commit_message: 'Updated readme with the latest stackOverflow data'
          feed_list: 'https://stackoverflow.com/feeds/user/9578353'
          committer_email: 'msrajawat298@gmail.com'
          committer_username: 'msrajawat298'
          commit_message: 'Updated readme with the latest stackOverflow data'
